#!/usr/bin/env sh
echo "Deploy script for Astro"

dist_client=./dist/client
dist_server=./dist/server
backup_client=./backup/client
backup_server=./backup/server
dist_server_logs="$dist_server/logs"
backup_server_logs="$backup_server/logs"


# create folder structure for backup
mkdir -p $backup_client
mkdir -p $backup_server_logs

# save .htaccess for NodeJs application
if [ -f $dist_client/.htaccess ]; then
  mv $dist_client/.htaccess $backup_client/
fi

#  save the server logs
if [ -d $dist_server_logs ]; then
  if ls $dist_server_logs/*.log >/dev/null 2>&1 ; then
    mv $dist_server_logs/*.log $backup_server_logs/
  fi
fi

# install dependencies in ci mode
npm ci --cache ~/.npm --prefer-online --no-audit
# build the app will erase/overwrite the dist folder
npm run build

# add the .shtml of 404 in case it is used by host provider
  if [ -f $dist_client/404.html ]; then
  cp $dist_client/404.html $dist_client/404.shtml
fi

# restore .htaccess for NodeJs application
if [ -f $backup_client/.htaccess ]; then
  mv $backup_client/.htaccess $dist_client/
fi

# restore the server logs
mkdir -p $dist_server_logs
if [ -d $backup_server_logs ]; then
  if ls $backup_server_logs/*.log >/dev/null 2>&1; then
    mv $backup_server_logs/*.log $dist_server_logs/
  fi
fi

# generate the node application entry point
if [ -d $dist_server ]; then
  echo "import(\"./entry.mjs\");" > "$dist_server/entry.cjs"
fi
